"""Render motds.json + README.template.md -> README.md.

Pure function. No environment lookups (except `date.today()` when run as
a script). Stdlib only. Idempotent: same inputs -> same bytes.
"""
import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MOTDS_PATH = ROOT / "motds.json"
TEMPLATE_PATH = ROOT / "README.template.md"
README_PATH = ROOT / "README.md"

DO_NOT_EDIT = "<!-- generated by build_readme.py; do not edit -->"
ARCHIVE_LIMIT = 7


def render(motds: list[dict], today: date, template: str) -> str:
    """Build README text from the motds list, today's date, and the template.

    The template must contain the literal placeholder `{{MOTD_BLOCK}}`.
    """
    today_str = today.isoformat()

    # Dedupe by date, keeping the entry with the latest posted_at per date.
    # `posted_at` is required — fail loudly on malformed input rather than
    # silently picking an order-dependent winner. Ties go to the later entry
    # (>=) so a same-second rewrite has well-defined semantics.
    by_date: dict[str, dict] = {}
    for i, entry in enumerate(motds):
        if "date" not in entry or "posted_at" not in entry:
            raise ValueError(
                f"motds[{i}] missing required key 'date' or 'posted_at': {entry!r}"
            )
        prev = by_date.get(entry["date"])
        if prev is None or entry["posted_at"] >= prev["posted_at"]:
            by_date[entry["date"]] = entry

    todays = by_date.get(today_str)
    others_desc = sorted(
        (e for d, e in by_date.items() if d != today_str),
        key=lambda e: e["date"],
        reverse=True,
    )

    if todays is None and not others_desc:
        motd_block = "> _No MOTD yet — the routine fires daily at 9am PT._"
    else:
        primary = todays or others_desc[0]
        if todays is None:
            others_desc = others_desc[1:]
        motd_block = f"> **{primary['date']}** — {primary['text']}"

    archive = others_desc[:ARCHIVE_LIMIT]
    if archive:
        lines = ["", "<details>", "<summary>Past MOTDs</summary>", ""]
        for e in archive:
            lines.append(f"- **{e['date']}** — {e['text']}")
        lines.extend(["", "</details>"])
        motd_block += "\n" + "\n".join(lines)

    body = template.replace("{{MOTD_BLOCK}}", motd_block)
    if not body.startswith(DO_NOT_EDIT):
        body = DO_NOT_EDIT + "\n" + body
    return body


def main() -> None:
    motds = json.loads(MOTDS_PATH.read_text())
    template = TEMPLATE_PATH.read_text()
    readme = render(motds, date.today(), template)
    README_PATH.write_text(readme)


if __name__ == "__main__":
    main()
