"""Unit tests for build_readme.py.

The renderer is pure: given (motds, today, template) -> readme_text.
Tests pass `today` explicitly so they don't depend on the system clock.
"""
import json
import unittest
from datetime import date
from pathlib import Path

import build_readme

FIXTURES = Path(__file__).parent / "fixtures"
TEMPLATE = """<!-- generated by build_readme.py; do not edit -->
# Test Header

{{MOTD_BLOCK}}

Footer"""


def load(name: str):
    return json.loads((FIXTURES / name).read_text())


class BuildReadmeTests(unittest.TestCase):
    def test_empty_motds_renders_no_motd_yet(self):
        readme = build_readme.render(load("empty.json"), date(2026, 5, 15), TEMPLATE)
        self.assertIn("No MOTD yet", readme)
        self.assertTrue(readme.startswith("<!-- generated by build_readme.py; do not edit -->"))

    def test_single_today_renders_today_text(self):
        readme = build_readme.render(load("single_today.json"), date(2026, 5, 15), TEMPLATE)
        self.assertIn("math52 midterm survived", readme)
        self.assertNotIn("<details>", readme)

    def test_single_old_falls_back_to_most_recent(self):
        readme = build_readme.render(load("single_old.json"), date(2026, 5, 15), TEMPLATE)
        self.assertIn("shipping VR Runner v2 today.", readme)
        self.assertNotIn("No MOTD yet", readme)

    def test_six_entries_show_today_plus_five_in_archive(self):
        readme = build_readme.render(load("six_entries_today.json"), date(2026, 5, 15), TEMPLATE)
        self.assertIn("math52 midterm survived", readme)
        archive_start = readme.index("<details>")
        archive = readme[archive_start:]
        for snippet in ("midterm tonight", "ps3 in.", "231n midterm done.", "lit review", "shipping VR Runner"):
            self.assertIn(snippet, archive, f"archive missing: {snippet}")
        self.assertEqual(readme.count("math52 midterm survived"), 1)

    def test_ten_entries_archive_caps_at_seven(self):
        readme = build_readme.render(load("ten_entries_today.json"), date(2026, 5, 15), TEMPLATE)
        archive = readme[readme.index("<details>"):]
        self.assertIn("entry minus two.", archive)
        self.assertIn("entry minus three.", archive)
        self.assertNotIn("entry six days ago.", archive)
        self.assertNotIn("entry five days ago.", archive)

    def test_replace_today_uses_later_posted_at(self):
        readme = build_readme.render(load("replace_today.json"), date(2026, 5, 15), TEMPLATE)
        self.assertIn("replaced text.", readme)
        self.assertNotIn("first take.", readme)

    def test_output_is_byte_identical_when_rerendered(self):
        motds = load("six_entries_today.json")
        a = build_readme.render(motds, date(2026, 5, 15), TEMPLATE)
        b = build_readme.render(motds, date(2026, 5, 15), TEMPLATE)
        self.assertEqual(a, b)

    def test_missing_posted_at_raises(self):
        motds = [{"date": "2026-05-15", "text": "no timestamp"}]
        with self.assertRaises(ValueError) as ctx:
            build_readme.render(motds, date(2026, 5, 15), TEMPLATE)
        self.assertIn("posted_at", str(ctx.exception))

    def test_dedupe_tie_uses_later_entry(self):
        # Two entries for the same date with IDENTICAL posted_at — later wins.
        motds = [
            {"date": "2026-05-15", "text": "earlier", "style": "terse",
             "posted_at": "2026-05-15T09:00:00-07:00"},
            {"date": "2026-05-15", "text": "later",   "style": "casual",
             "posted_at": "2026-05-15T09:00:00-07:00"},
        ]
        readme = build_readme.render(motds, date(2026, 5, 15), TEMPLATE)
        self.assertIn("later", readme)
        self.assertNotIn("earlier", readme)


if __name__ == "__main__":
    unittest.main()
